### ISSUE TITLE
Howto validate MongoDB instances?

### ISSUE THREAD

**Issue by dvv** [akidee/schema.js#2]
Hi!

MongoDB as primary keys uses `_id` properties. When non-strict validating such instances `_id` just gets deleted. How do I specify the default primary key name? Or should I specify it explicitly in every `type: 'object'` schema?

TIA,
--Vladimir

**Comment by akidee** [comment]
You can define it explicitly with "type: 'object'", or you add "additionalProperties: true", so you can add other properties, including _id. It's your decision.

**Comment by dvv** [comment]
I see. Thought may be `id` is treated as kinda intrinsic property. Thanks
--Vladimir

P.S. Would it be welcome to schema.js if I shared some drafts for fixtures based on json-schema?

--Vladimir

**Comment by akidee** [comment]
Fixtures - do you mean default schemas like address, geo point etc. ?

**Comment by dvv** [comment]
I mean a tool that can generate a bunch of instances filled with lorem ipsum data. I'll place the code to my fork of schema.js and ping you tomorrow (GMT+4 here)

**Comment by akidee** [comment]
Place this one into a separate repository, that depends on schema.js - API could be like this:

```
loremIpsumInstances = require('json-schema-fixture')(myJsonSchema, 100);
```

Good idea - I am interested, this is especially useful for automated testing.

**Comment by dvv** [comment]
yep. I made http://gist.github.com/605284 to show the idea. Frankly, I'd like you to refactor it into a bunch of pluggable methods, as you did in schema.js. That is why I thought it could be a plugin to schema.js schema walk routine, say, as a special kind of a fallback, which overrides `default: ...`. That way we'd conforme the ideology of schema.js

What do you think?

**Comment by akidee** [comment]
1) This is your job ;)
2) Think of my model. There is Schema and Schema.Validation - what you want to do is Schema.Fixture - the properties you add to the schema for the fixture do not touch the validation, but it would be useful if you stick to a standard for fixture generation, if there is one. This has nothing to do with the walk routine, of course if would be great, if it is modular and _implemented like Schema.Validation_. To use Schema.Validation to generate fixtures is possible but misleading, because then you need a second schema for fixture generation.
3) I think of the next use for Schema: Schema.UI.

To conclude: Schema is for representing a Schema, Schema.x is for doing x with a schema.

**Comment by dvv** [comment]
Hardly, to say the truth... I planned to just add custom fallbacks and order to use them when validating. Particular parameters for generating particular datatypes could be specified as settings.

**Comment by akidee** [comment]
It is better, if you do not add it to schema.js ;) I have put a lot thoughts into the Schema.x way of doing it.
As far as I understand you, it is very easy to transform my Validation implemantation to Schema.Fixture! Fallbacks are just there for validation, so if you use them for generating data, you cannot use _1_ schema both for validation and fixture generation.
